### ISSUE TITLE
output interpretation

### ISSUE THREAD

**Issue by deschec** [morrislab/qapa#17]
Greetings:

I am not sure i fully understand the output for the APD_ID.  I understand that for a Single APA_ID, one should expect only one "S" APA_ID.  When the output lists a proximal "P" APA_ID, I would expect at least one matching distal "D" APA_ID.  In some cases, the sum of the PAU scores for the proximal and distal  amount to 100.  In other cases, either the sum of all APA_ID's does not amount to 100, or the proximal APA_ID is the only one, with no distal site being listed.  Does that mean that there are other APA sites than the proximal one, but that they can not be identified by the annotation library?  And in such cases, do differences in PPAU  indicate the putative existence of at least one distal site?

Also: to what does "NA" correspond to?  Is it different from zero?

Apologies in advance if these questions are too naive, but I am very keen on trying this tool on my set of biologic data.

Thank you in advance.

 .  Concerning the APA APA_ID

**Comment by deschec** [comment]
One other comment related to the above questions...  One example of that is that of a transcript that lists 5 "Num_events", but only two APA_ID's, with the sum of the PAU scores of the latter being much less than 100.  How should this be interpreted?

**Comment by kcha** [comment]
Hi @deschec, 
Thanks for your questions. It may be possible that a gene contains an alternative last exon which might cause this. But those cases should be ignored by QAPA unless it missed it due to a scenario that I have not encountered before. Did you create your own 3' UTR library from scratch or with a new species?

An "NA" in APA_ID is likely due to an error in matching gene identifiers between the genePred file and the Ensembl identifiers file.

"Num_events" should correspond to the number of APA_IDs for a gene.
