### ISSUE TITLE
Looking at 5-utr/first Exon usage

### ISSUE THREAD

**Issue by seq101** [morrislab/qapa#18]
Thank you so much for developing Qapa- it is amazingly easy and very helpful.i was able to get some awesome results in an afternoon for a new species.

This is not an issue but I am wondering if there is a way to hack Qapa to look at the first exon or 5’utr  instead of the 3’utr.

I have the fasta sequence of the first exon and have run salmon on it. But now I need to feed it to qapa to get first exon “PAU”.

Also, how is PAU calculated exactly? The paper states that it’s expression of utr divided by expression of all the isoforms- how does it decipher the expression of all isoforms via samlons quantification? A deeper explanation on this would also be helpful to think about looking at the first exon differential usage.

**Comment by kcha** [comment]
Hi @seq101, thanks for your interest and question. Your idea of 5' UTR idea is something I have thought of, but not actively being pursued. The key will be to have a 5' UTR library with well-defined start and end boundaries. We did look at alternative transcriptional start sites in our paper, but that involved a manual approach rather than trying to adapt QAPA.

PAU is simply a ratio of a 3' UTR isoform expression over the sum of 3' UTR isoforms for a given gene. Salmon is used to get the expression quantifications for each isoform. So instead of supplying a 3' UTR library to Salmon, you would use a 5' UTR library. QAPA would also need to be modified to know how to handle 5' UTRs.

**Comment by seq101** [comment]
Thanks for the quick reply! I have the 5’utr library and start and stop coordinates. I have also run salmon on it. Would it possible for you to give me more pointers on how to modify qapa for dealing with calculating pau ratio? I would absolutely cite your paper and mention this modification in my paper.  

Would it work if I changed the gene annotation file such that the stop coding would be the start of the transcript and end of the gene would be actually the end of the first Exon? Does qapa need to know demarcation of all Exons for pau calculation?

Another option would be to reverse the gene annotation such that the 5’utr becomes the 3’utr- seems like this may work? Does the strand matter? I have the sequences extracted so only talking about the quant step of qapa.

**Comment by kcha** [comment]
If you have the quantifications already, then it may be possible to modify the `quant` step , which exeecutes the two R scripts `create_merged_data.R` and `compute_pau.R`. Essentially it will be required to change all references and logic regarding 3' UTRs to deal with 5' UTRs. 

Swapping the coordinates is a clever idea. It's possible that this will work as I don't make any strong assertions about start coordinates being less than end coordinates (there are such assertions in the `build` step). Strand does matter because they are treated differently. For 3' UTRs on the forward strand, the start coordinates of all 3' UTR isoforms of a gene must match, while on the reverse strand the end coordinates must match. For 5' UTRs these would be reversed.
