### ISSUE TITLE
 some columns are not in the data.table: Gene

### ISSUE THREAD

**Issue by dktanwar** [morrislab/qapa#30]
```bash
compute_pau.R tab_new.txt
```

```
Error in setkeyv(x, cols, verbose = verbose, physical = physical) :
    some columns are not in the data.table: Gene
Calls: setkey -> setkeyv
Execution halted|
```

**Comment by dktanwar** [comment]
```
Merging samples by TPM
  |======================================================================| 100%
Separating Ensembl IDs
Adding Ensembl metadata
Found 57084/135894 (42.01%) matches
Error in colnamesInt(x, neworder, check_dups = TRUE) :
  argument specifying columns specify non existing column(s): cols[4]='Chr'
Calls: add_ensembl_metadata -> setcolorder -> colnamesInt
In addition: Warning messages:
1: In separate_ensembl_field(merged_data) :
  Unable to find Ensembl IDs by regex
2: In add_ensembl_metadata(merged_data, opt$options$db, opt$options$all_genes,  :
  A large proportion of events could not be matched to the annotation. This could suggest a possible issue with the database used. In a typical run, all of the events have a match since the 3' UTR library should have been built using the same database file.
Execution halted
qapa.qapa     - 2019-10-15 14:17:49,940 - INFO     - compute_pau.R -e quant.sf
[1] "en_US.utf8"
Error in setkeyv(x, cols, verbose = verbose, physical = physical) :
  some columns are not in the data.table: Gene
Calls: setkey -> setkeyv
Execution halted
qapa.qapa     - 2019-10-15 14:17:50,361 - INFO     - Finished!
```

**Comment by kcha** [comment]
The error might be suggesting you are using the incorrect `ensembl_identifiers` file for your species. On a normal run, you should get 100% match of records.

**Comment by JamalEH** [comment]
Hi,

I'm having the same issue here!

Could you please provide in a more clear way the steps that one has to follow for using Gencode GTF file. Why do we need to use "-db ensembl_identifiers_mm10.txt" file if we are using Gencode annotation? Wouldn't be enough to just grep the same information from gencode.gtf file? 

Does transcript ids with version works as well? in my hands they dont!

Best regards,
Jamal.

**Comment by JamalEH** [comment]
Dear Team,

I solved the problem.
I had to run Salmon expression quantification step providing the index that was created using the output_sequences.fa file obtained from the previous step. So one has to make sure to run Salmon on the read files but providing the index created with the file "output_sequences.fa".

I hope this may help other users.
Kind regards,
Jamal.

**Comment by jingfong12** [comment]
Hey, hello! I’m a bit confused about why I’m getting errors even though I’m using the same db file. Could you please help me take a look?

When constructing the index, I used the same db file, and based on this db file, I performed Salmon quantification, which generated the quant.sf file. However, I’m encountering errors during the QAPA quant step. Could you kindly help me identify the issue?

Here is my db file content:
Gene stable ID | Transcript stable ID | Gene type | Transcript type | Gene name
ENSBTAG00000006648 | ENSBTAT00000008737 | protein_coding | protein_coding |
ENSBTAG00000006648 | ENSBTAT00000007786 | protein_coding | protein_coding |
ENSBTAG00000049697 | ENSBTAT00000082524 | rRNA | rRNA | 5S_rRNA
ENSBTAG00000047028 | ENSBTAT00000063709 | rRNA | rRNA | 5S_rRNA
ENSBTAG00000053686 | ENSBTAT00000065353 | rRNA | rRNA | 5S_rRNA

Here is my quant.sf file content:
Name | Length | EffectiveLength | TPM | NumReads
XM_024997782.1(+) | 208 | 25.301 | 0.000000 | 0.000
XM_024997783.1(+) | 4691 | 4418.173 | 2.086016 | 140.845
NM_001206853.1(+) | 4409 | 4136.173 | 9.108687 | 575.750
XM_024997900.1(+) | 3370 | 3097.173 | 0.401429 | 19.000

Thank you so much for your help!

**Comment by jingfong12** [comment]
(qapa)[99017@cnode2015 APA]$ qapa quant --db ./emsembl_1.2.txt ./APA_res/220368C_2B1/                              quant.sf >pau_result.txt
qapa.qapa     - 2024-11-28 16:28:27,712 - INFO     - Version 1.3.3
qapa.qapa     - 2024-11-28 16:28:27,712 - INFO     - create_merged_data.R --db ./emse                              mbl_1.2.txt -f TPM -F salmon ./APA_res/220368C_2B1/quant.sf > /tmp/qapa_merge_w0n4n7k                              f
Merging samples by TPM
  |                                                                      |   0%Separa                              ting Ensembl IDs
Adding Ensembl metadata
Found 0/23377 (0.00%) matches
Error in colnamesInt(x, neworder, check_dups = FALSE) :
  指定列的参数受到了不存在的列: cols[4]='Chr'
Calls: add_ensembl_metadata -> setcolorder -> colnamesInt
此外: Warning messages:
1: In separate_ensembl_field(merged_data) :
  Unable to find Ensembl IDs by regex
2: In add_ensembl_metadata(merged_data, opt$options$db, opt$options$all_genes,  :
  No annotation matches were found. Are you using the correct database?
3: In add_ensembl_metadata(merged_data, opt$options$db, opt$options$all_genes,  :
  A large proportion of events could not be matched to the annotation. This could sug                              gest a possible issue with the database used. In a typical run, all of the events hav                              e a match since the 3' UTR library should have been built using the same database fil                              e.
停止执行
qapa.qapa     - 2024-11-28 16:28:28,591 - INFO     - compute_pau.R -e /tmp/qapa_merge                              _w0n4n7kf
Error in read.table(file = file, header = header, sep = sep, quote = quote,  :
  输入中没有多出的行
Calls: data.table -> read.csv -> read.table
停止执行
qapa.qapa     - 2024-11-28 16:28:29,005 - INFO     - Finished!
