### ISSUE TITLE
Apply quality filtration on PAU

### ISSUE THREAD

**Issue by obenno** [morrislab/qapa#7]
Hi @kcha,

I performed qapa with default parameters on my data, the correlation of the replicates were mess up (Pearson correlation, hclust with ward.D2 method), but they could be clustered together when using TPM value. May I ask for your suggestions on filtering APA events? I noticed there is an experimental option for compute_pau.R. If filtering PAU with its beta distribution standard deviation, what cut off do you think is proper? Any advice that you can give me would be greatly appreciated. 

Bests,
obenno

**Comment by kcha** [comment]
Hi @obenno, you can try removing genes that are lowly expressed across your samples. e.g. remove genes with total gene expression less than 3 TPM. As PAU is a ratio of expression values, lowly expressed genes may make PAU estimates less reliable. The standard deviation option was an option I added in the early stages of development as a confidence measure. Since then I haven't really be working on it or used it. If you want to try using it you will have to play around with different thresholds.

**Comment by obenno** [comment]
Hi @kcha,

Thank you very much! I have already filtered TPM with your criteria, but the correlation among replicates is still bad. I may try much stricter filtration on TPM. 

One more thing, in the annotation step, if the PAS is upstream of cds end position, it will be ignored, is it?

**Comment by kcha** [comment]
That's correct. We currently don't look upstream of the CDS.

**Comment by obenno** [comment]
Thanks for your reply. Since I have many cases that transcripts pre-stop before cds end, I used last.exon.start and last.exon.end to fake cds start and stop.

**Comment by kcha** [comment]
With your modification, beware of producing intervals that are too short careful (< ~100 nt). These may not be measured accurately for expression.
